baseurl = ""
languageCode = "en-us"
title = "Look on Loom"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
publishDir = "docs"

[params]
	# General information
	author = "Robert Morgan"
	description = "Look on Loom"
	copyright = "Robert Morgan"

	# Repository
	provider = "GitHub"
	repo_url = ""

	version = ""
	logo = "/static/Loomlogo.svg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "amber"

    [params.font]
    	text = "Open Sans"
    	code = "Open Sans"


[social]
	twitter = ""
	github  = ""
	email   = "hello@email.com"


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


[[menu.main]]
	name   = "Conveyancing"
	url    = "conveyancing/"
	weight = 10

[[menu.main]]
	name   = "Your stories"
	url    = "your-stories/"
	weight = 20

[[menu.main]]
	name   = "Find a Conveyancer"
	url    = "find-a-conveyancer/"
	weight = 30

[[menu.main]]
	name   = "Loom Legal Outsourcing"
	url    = "outsourcing/"
	weight = 35


[[menu.main]]
	name   = "T&Cs"
	url    = "legal/"
	weight = 40

[[menu.main]]
	name   = "**Notes on building this website**"
	url    = "robert/"
	weight = 50


[[menu.main]]
	name   = "About Loom"
	url    = "about/"
	weight = 60
