baseurl = "https://example.org/"
languageCode = "en-us"
title = "Look on Loom"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Robert Morgan"
	description = "Look on Loom"
	copyright = "Loom Legal"

	# Repository
	provider = "GitHub"
	repo_url = ""

	version = ""
	logo = "/static/Loomlogo.svg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "grey"
    	accent  = "amber"

    [params.font]
    	text = "Helvetica Neue"
    	code = "Helvetica Neue"


[social]
	twitter = ""
	github  = "digitalcraftsman"
	email   = "hello@email.com"


[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40

[[menu.main]]
	name   = "Rob"
	url    = "robert/"
	weight = 50


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
